### ISSUE TITLE
【适配请求】适配 koishi-plugin-puppeteer 提供的 canvas 服务 / 适配 canvas 服务接口

### ISSUE THREAD

**Issue by manipEgo** [araea/koishi-plugin-p5-advance-letter-generator#1]
[koishi-plugin-puppeteer](https://github.com/koishijs/koishi-plugin-puppeteer) 可提供与当前依赖的 koishi-plugin-canvas 相同的 canvas 服务。同时启用多个提供者时，只有首先启用的一个能够生效。这会产生一些不稳定性，可能导致本插件无法正常工作。

并且，需要指定的服务插件才能正常工作似乎与“服务”这层抽象的目的相悖。

请求适配 koishi-plugin-puppeteer，或如果可能，全面适配 canvas 服务接口，取消对特定 canvas 插件的依赖。

**Comment by araea** [comment]
# 适配成功！ 

## 插件版本 v1.0.1 及更高版本已成功适配puppeteer插件提供的canvas服务！

![image](https://github.com/araea/koishi-plugin-p5-advance-letter-generator/assets/120614554/b18f3bb6-56f1-46ad-8999-d2e6c83f4193)

## 如果您在之前的版本中不小心更新了插件，

## 那么，在将插件更新至目标版本后，

## 请前往下图所示的文件目录，删除两个HTML文件，并重新启动插件。

![image](https://github.com/araea/koishi-plugin-p5-advance-letter-generator/assets/120614554/936d415d-67e2-4de3-84a0-3628bed32e24)

## 使用 puppeteer 后的效果图示例（可能会与 canvas 的效果有轻微的出入）：

![image](https://github.com/araea/koishi-plugin-p5-advance-letter-generator/assets/120614554/bd8e828e-98a1-4005-8313-7afa37c2e7a9)
